version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: jera-test
    environment:
      MYSQL_ROOT_PASSWORD: jeratest
      MYSQL_DATABASE: jeraflix_db
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
